#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("eShopOnContainers.Droid.Resource", IsApplication=true)]

namespace eShopOnContainers.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int white = 2130771968;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int app_settings = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int background = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int banner = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int default_campaign = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int default_product = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int fake_campaign_01 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int fake_campaign_02 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int fake_product_01 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int fake_product_02 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int fake_product_03 = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int fake_product_04 = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int fake_product_05 = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int header_logo = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int icon = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int menu_campaigns = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int menu_cart = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int menu_filter = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int menu_profile = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int noimage = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int product_add = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int switch_off = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int switch_on = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int linearLayout_Home = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int sliding_tabs = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int tab_icon = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int tab_layout_textview = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int toolbar = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int toolbar_image = 2130903045;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int TabLayout = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Tabs = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int Toolbar = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F050000
			public const int AppCompatDialogStyle = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int MainTheme = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int MainTheme_Base = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int Theme_Splash = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
